/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snda_Andro7z_Andro7za */

#ifndef _Included_com_snda_Andro7z_Andro7za
#define _Included_com_snda_Andro7z_Andro7za
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snda_Andro7z_Andro7za
 * Method:    a7za_print_usage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_snda_Andro7z_Andro7za_a7za_1print_1usage(JNIEnv *env, jobject obj, jstring _pathArchive, jstring _pathToExtract);

#ifdef __cplusplus
}
#endif
#endif
